#!/usr/bin/env bash
# Bundle lib.sh + steps.sh + main.sh into a single curl-able dist/provision.sh.
#
#   scripts/provision/build.sh [VERSION]
#
# The whole body is wrapped in one function that is called on the last line, so
# a download truncated anywhere in the middle is a syntax error at EOF and
# executes nothing. That is what makes `curl ... | bash` safe here.
set -Eeuo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
OUT="$HERE/dist/provision.sh"
VERSION="${1:-0.0.0-dev}"

if [[ ! "$VERSION" =~ ^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(-[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?(\+[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?$ ]]; then
  echo "invalid semantic version: $VERSION" >&2
  exit 2
fi

mkdir -p "$HERE/dist"
{
  echo '#!/usr/bin/env bash'
  echo '# Hive provision.sh — generated by scripts/provision/build.sh; do not edit directly.'
  echo "SCRIPT_VERSION=\"$VERSION\""
  echo '__hive_provision() {'
  # `shell=bash` directives belong at the top of a file; inside the wrapper they
  # would be misplaced, so they are dropped from the bundle.
  grep -hv '^# shellcheck shell=bash$' "$HERE/lib.sh" "$HERE/steps.sh" "$HERE/main.sh"
  echo '}'
  echo '__hive_provision "$@"'
} >"$OUT"
chmod +x "$OUT"

if command -v shellcheck >/dev/null 2>&1; then
  shellcheck -S warning "$OUT" || { echo "shellcheck failed" >&2; exit 1; }
else
  echo "warning: shellcheck not installed; the bundle was not linted" >&2
fi

echo "built $OUT (version $VERSION)"
