#!/usr/bin/env bash
# Bundle lib.sh + steps.sh + main.sh into a single curl-able dist/provision.sh.
# The whole script is wrapped so a truncated download executes nothing.
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
OUT="$HERE/dist/provision.sh"
VERSION="${1:-0.0.0-dev}"

if [[ ! "$VERSION" =~ ^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(-[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?(\+[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?$ ]]; then
  echo "invalid semantic version: $VERSION" >&2
  exit 2
fi

mkdir -p "$HERE/dist"
{
  echo '#!/usr/bin/env bash'
  echo "# Hive provision.sh — generated by build.sh; do not edit directly."
  echo "SCRIPT_VERSION=\"$VERSION\""
  cat "$HERE/lib.sh"
  cat "$HERE/steps.sh"
  cat "$HERE/main.sh"
} >"$OUT"
chmod +x "$OUT"

if command -v shellcheck >/dev/null 2>&1; then
  shellcheck -S warning "$OUT" || { echo "shellcheck failed" >&2; exit 1; }
fi
echo "built $OUT (version $VERSION)"
