import type { AgentActivity } from "@hive/shared/agent-activity";
export type { AgentActivity, AgentActivityCommandAction, AgentActivityFile } from "@hive/shared/agent-activity";

export interface Project {
  id: string;
  name: string;
  url: string;
  createdAt: string;
}

export type WorkspaceStatus = "idle" | "busy";

export interface Workspace {
  id: string;
  name: string;
  projectId: string;
  branch: string;
  status: WorkspaceStatus;
  createdAt: string;
  activeSessionId?: string;
  lastActivityAt?: string;
}

// ── Completion / autocomplete types ─────────────────────────────────

export type CompletionItemType = "slash_command" | "agent";
export type CompletionSource =
  | "builtin"
  | "user_command"
  | "project_command"
  | "user_skill"
  | "project_skill"
  | "admin_skill"
  | "plugin"
  | "user_agent"
  | "project_agent";

export interface CompletionItem {
  type: CompletionItemType;
  name: string;
  label: string;
  /** Native text sent to the provider when Hive displays a different trigger. */
  replacementLabel?: string;
  description?: string;
  argumentHint?: string;
  source: CompletionSource;
}

export interface CompletionsResponse {
  items: CompletionItem[];
}

// ── Branch / GitHub sync types ──────────────────────────────────────

export interface PullRequestInfo {
  number: number;
  url: string;
  state: "open" | "draft" | "merged" | "closed";
  mergeable: boolean | null;
  mergeableState: "clean" | "conflict" | "blocked" | "unstable" | "unknown";
  checksStatus: "pending" | "success" | "failure" | "cancelled";
  checksPassed: number | null;
  checksTotal: number | null;
  reviewStatus: "approved" | "changes_requested" | "review_required" | null;
}

export interface BranchInfo {
  name: string;
  lastSyncedAt: string;
}

export interface PrStatusResponse {
  pr: PullRequestInfo | null;
  error?: string;
}

export interface BulkPrStatusResponse {
  results: Record<string, PrStatusResponse>;
}

export interface WorkspaceFileTreeNode {
  name: string;
  path: string;
  type: "file" | "directory";
  children?: WorkspaceFileTreeNode[];
}

export interface ProjectState {
  id: string;
  name: string;
  url?: string;
  createdAt: string;
  workspaces: Workspace[];
}

export type {
  ProjectEnvConfig,
  ProjectEnvData,
  ProjectEnvVariable,
} from "@hive/shared/project-env";

export type CreateProjectRequest =
  | { mode?: "clone"; url: string }
  | { mode: "create"; name: string; visibility?: "public" | "private" };

// ── Image attachment type ────────────────────────────────────────────

export interface ImageAttachment {
  name: string;
  mediaType: string;
  dataUrl: string;
}

// ── File mention type ───────────────────────────────────────────────

export interface FileMention {
  displayName: string;   // e.g. "git.ts" or "api/index.ts" (disambiguated)
  relativePath: string;  // e.g. "src/utils/git.ts"
}

// ── Session / Chat types ────────────────────────────────────────────

export interface SessionMetadata {
  sessionId: string;
  /** Provider-native conversation/thread id used for resume across turns. */
  providerSessionId?: string;
  /** @deprecated Use providerSessionId. Kept for old persisted sessions. */
  claudeSessionId?: string;
  workspaceId: string;
  title?: string;
  createdAt: string;
  updatedAt: string;
  messageCount: number;
  /** Provider ID locked on first message (e.g. "claude" or "codex"). */
  lockedProvider?: string;
}

export interface ToolCall {
  id: string;
  name: string;
  input: string;
  output?: string;
  parentToolUseId?: string;
}

export interface ChatMessage {
  id: string;
  sessionId: string;
  role: "user" | "assistant";
  content: string;
  images?: ImageAttachment[];
  fileMentions?: FileMention[];
  toolCalls?: ToolCall[];
  agentActivities?: AgentActivity[];
  thinkingContent?: string;
  timestamp: string;
  cancelled?: boolean;
  /** Extra diagnostics for interrupted turns (stderr summary, exit code). */
  errorDetail?: string;
  durationMs?: number;
  /** Total input tokens sent to the model for this turn. */
  inputTokens?: number;
  /** Output tokens generated by the model for this turn. */
  outputTokens?: number;
  /** Tokens currently occupying the model context window. */
  contextUsedTokens?: number;
  /** Context window size reported by the provider for this turn. */
  contextWindowTokens?: number;
}

// ── Claude CLI NDJSON types (--print --output-format stream-json --verbose) ──

/** Content block within an assistant message */
export type ServerToolResultType =
  | "web_search_tool_result"
  | "web_fetch_tool_result"
  | "bash_code_execution_tool_result"
  | "text_editor_code_execution_tool_result";

export type ContentBlock =
  | { type: "text"; text: string }
  | { type: "tool_use"; id: string; name: string; input: unknown; parentToolUseId?: string }
  | { type: "server_tool_use"; id: string; name: string; input: unknown }
  | { type: "mcp_tool_use"; id: string; name: string; server_name: string; input: unknown }
  | { type: ServerToolResultType; tool_use_id: string; content: unknown }
  | { type: "mcp_tool_result"; tool_use_id: string; is_error: boolean; content: unknown }
  | { type: "thinking"; thinking: string }
  | { type: "redacted_thinking"; data: string };

/** Tool result block within a user message */
export interface ToolResultBlock {
  type: "tool_result";
  tool_use_id: string;
  content: string;
}

export type CliJsonLine =
  | {
      type: "assistant";
      message: {
        id: string;
        role: "assistant";
        content: ContentBlock[];
        model?: string;
        stop_reason?: string;
        usage?: {
          input_tokens: number;
          output_tokens: number;
          cache_creation_input_tokens?: number;
          cache_read_input_tokens?: number;
        };
      };
    }
  | {
      type: "user";
      message: {
        role: "user";
        content: ToolResultBlock[];
      };
    }
  | {
      type: "result";
      session_id: string;
      cost_usd?: number;
      duration_ms?: number;
      /** Provider-specific terminal status for protocol-backed runners. */
      status?: string;
      /** Provider-specific terminal error detail for failed turns. */
      error?: string;
      /** Codex/Gemini adapters may place usage here; Claude puts it on assistant events. */
      usage?: {
        input_tokens: number;
        output_tokens: number;
        cache_creation_input_tokens?: number;
        cache_read_input_tokens?: number;
        context_used_tokens?: number;
        context_window?: number;
      };
    }
  | {
      type: "system";
      message: string;
      level?: string;
    };

// ── Script types ─────────────────────────────────────────────────────

export type ScriptType = string;
export type ScriptState = "idle" | "running" | "done" | "error";

export interface HiveConfig {
  scripts?: { setup?: string; run?: Record<string, string> };
  port?: number;
}

export interface ScriptStatusInfo {
  state: ScriptState;
  exitCode?: number;
}

export interface WorkspaceScriptsResponse {
  config: HiveConfig | null;
  status: Record<string, ScriptStatusInfo>;
}

// ── Diff types ───────────────────────────────────────────────────────

export type DiffFileStatus = "added" | "modified" | "deleted" | "renamed";
export type DiffScope = "combined" | "committed" | "uncommitted";

export interface DiffFileStat {
  file: string;
  additions: number;
  deletions: number;
  status: DiffFileStatus;
  renamedFrom?: string;
}

export interface DiffStatResponse {
  committed: DiffFileStat[];
  uncommitted: DiffFileStat[];
}

// ── Interactive tool input types ─────────────────────────────────────

export type ToolInputResult =
  | { type: "answer"; answers: QuestionAnswer[]; questions?: QuestionInput[] }
  | { type: "approve" }
  | { type: "reject"; message?: string }
  | { type: "dismiss"; message?: string };

export interface QuestionAnswer {
  questionIndex: number;
  selectedOptions: number[];
  customText?: string;
}

export interface QuestionInput {
  question: string;
  options: Array<{ label: string; description?: string }>;
  multiSelect?: boolean;
}

// ── WebSocket protocol ──────────────────────────────────────────────

/** Per-message options that control agent CLI behavior. */
export interface MessageOptions {
  planMode?: boolean;
  /** Compound model ID: "provider:model", e.g. "claude:opus-4-7" or "codex:gpt-5.5" */
  model?: string;
  /** Reasoning effort level for providers that support it (Claude `--effort`, Codex `model_reasoning_effort`). */
  thinkingLevel?: ThinkingLevel;
}

export type ThinkingLevel = "none" | "minimal" | "low" | "medium" | "high" | "xhigh" | "max";

export type BrowserSessionState = "registered" | "active" | "closed" | "error";

export interface BrowserStatusPayload {
  sessionId: string;
  state: BrowserSessionState;
  streaming?: boolean;
  streamPath?: string;
  url?: string;
  title?: string;
  updatedAt: number;
  lastActiveAt?: number;
  error?: string;
}

/** Frontend -> Backend */
export type WsIncoming =
  | { type: "switch_session"; sessionId: string }
  | { type: "user_message"; content: string; images?: ImageAttachment[]; fileMentions?: FileMention[]; options?: MessageOptions; sessionId?: string }
  | { type: "stop"; sessionId?: string }
  | { type: "tool_input_response"; requestId: string; toolName: string; result: ToolInputResult; sessionId?: string };

/** Backend -> Frontend */
export type WsOutgoing =
  | { type: "text_delta"; sessionId: string; text: string }
  | { type: "thinking"; sessionId: string; text: string }
  | { type: "tool_use"; sessionId: string; id: string; name: string; input: string; parentToolUseId?: string }
  | { type: "tool_result"; sessionId: string; toolUseId: string; output: string }
  | { type: "agent_activity"; sessionId: string; activity: AgentActivity }
  | { type: "tool_input_required"; sessionId: string; requestId: string; toolName: string; toolUseId: string; input: unknown }
  | {
      type: "done";
      sessionId: string;
      durationMs?: number;
      inputTokens?: number;
      outputTokens?: number;
      contextUsedTokens?: number;
      contextWindowTokens?: number;
      pendingToolName?: string;
    }
  | { type: "error"; message: string; sessionId?: string }
  | { type: "cancelled"; sessionId: string; errorDetail?: string; userInitiated?: boolean; durationMs?: number }
  | { type: "status"; status: WorkspaceStatus; sessionId?: string; streaming?: boolean; streamingStartedAt?: number; lockedProvider?: string }
  | { type: "user_message"; message: ChatMessage }
  | { type: "history"; messages: ChatMessage[]; sessionId?: string }
  | { type: "branch_info"; info: BranchInfo }
  | { type: "diff_stats"; stats: DiffStatResponse }
  | { type: "script_status"; scriptType: ScriptType; state: ScriptState; exitCode?: number }
  | { type: "browser_status"; status: BrowserStatusPayload }
  | { type: "plan_mode_changed"; sessionId: string; active: boolean };

// ── Automation types ─────────────────────────────────────────────────

export type AutomationTriggerType = "cron";
export type AutomationActionType = "agent";
export type AutomationRunStatus = "running" | "success" | "failure";

export interface AutomationTrigger {
  type: AutomationTriggerType;
  expression: string;
}

export interface AutomationAction {
  type: AutomationActionType;
  modelId: string;
  systemPromptId?: string;
  systemPromptInline?: string;
  userPromptId?: string;
  userPromptInline?: string;
}

export interface AutomationNotification {
  onComplete: boolean;
  onFailure: boolean;
}

export interface Automation {
  id: string;
  name: string;
  enabled: boolean;
  projectId?: string;
  trigger: AutomationTrigger;
  action: AutomationAction;
  notification: AutomationNotification;
  workspacePath?: string;
  lastRunId?: string;
  lastRunAt?: string;
  lastRunStatus?: AutomationRunStatus;
  createdAt: string;
  updatedAt: string;
}

export interface AutomationRun {
  id: string;
  automationId: string;
  status: AutomationRunStatus;
  sessionId: string;
  startedAt: string;
  completedAt?: string;
  durationMs?: number;
  summary?: string;
  error?: string;
}

export interface PromptTemplate {
  id: string;
  name: string;
  type: "system" | "user";
  content: string;
  createdAt: string;
  updatedAt: string;
}

export interface CreateAutomationRequest {
  name: string;
  projectId?: string;
  trigger: AutomationTrigger;
  action: AutomationAction;
  notification?: AutomationNotification;
}

export interface UpdateAutomationRequest {
  name?: string;
  enabled?: boolean;
  trigger?: AutomationTrigger;
  action?: AutomationAction;
  notification?: AutomationNotification;
}

export interface CreatePromptTemplateRequest {
  name: string;
  type: "system" | "user";
  content: string;
}

export interface UpdatePromptTemplateRequest {
  name?: string;
  content?: string;
}

// ── Global skills settings ──────────────────────────────────────────

export type SkillProviderId = "claude" | "codex";
export type SkillSyncStatus =
  | "linked"
  | "synced"
  | "claude_only"
  | "codex_only"
  | "diverged"
  | "invalid";

export interface SkillProviderState {
  present: boolean;
  path: string;
  folderName?: string;
  isSymlink?: boolean;
  realPath?: string;
  hash?: string;
  updatedAt?: string;
  error?: string;
}

export interface SkillSummary {
  id: string;
  name: string;
  folderName: string;
  description?: string;
  argumentHint?: string;
  userInvocable: boolean;
  syncStatus: SkillSyncStatus;
  providers: Record<SkillProviderId, SkillProviderState>;
  invalidReason?: string;
  updatedAt?: string;
}

export interface SkillDetail extends SkillSummary {
  content: string;
  contentProvider: SkillProviderId;
  providerContents: Partial<Record<SkillProviderId, string>>;
}

export interface SkillListResponse {
  skills: SkillSummary[];
}

export interface CreateSkillRequest {
  content: string;
}

export interface UpdateSkillRequest {
  content: string;
}

export interface SkillSyncResponse {
  skills: SkillSummary[];
  syncedCount: number;
}

// ── Global instructions settings ────────────────────────────────────

export type InstructionProviderId = "claude" | "codex";
export type InstructionSyncStatus =
  | "missing"
  | "linked"
  | "synced"
  | "claude_only"
  | "codex_only"
  | "diverged"
  | "invalid";

export interface InstructionProviderState {
  present: boolean;
  path: string;
  isSymlink?: boolean;
  realPath?: string;
  hash?: string;
  updatedAt?: string;
  error?: string;
}

export interface InstructionOverrideState {
  present: boolean;
  active: boolean;
  path: string;
  hash?: string;
  size?: number;
  updatedAt?: string;
  error?: string;
}

export interface InstructionDetail {
  content: string;
  contentProvider: InstructionProviderId | null;
  syncStatus: InstructionSyncStatus;
  providers: Record<InstructionProviderId, InstructionProviderState>;
  providerContents: Partial<Record<InstructionProviderId, string>>;
  invalidReason?: string;
  updatedAt?: string;
  override: InstructionOverrideState;
}

export interface UpdateInstructionsRequest {
  content: string;
}

// ── Global custom agent settings ────────────────────────────────────

export type CustomAgentProviderId = "claude" | "codex";
export type CustomAgentStatus =
  | "both"
  | "claude_only"
  | "codex_only"
  | "invalid";

export interface CustomAgentProviderState {
  present: boolean;
  path: string;
  fileName?: string;
  isSymlink?: boolean;
  realPath?: string;
  hash?: string;
  updatedAt?: string;
  error?: string;
}

export interface CustomAgentSummary {
  id: string;
  name: string;
  description?: string;
  status: CustomAgentStatus;
  providers: Record<CustomAgentProviderId, CustomAgentProviderState>;
  invalidReason?: string;
  updatedAt?: string;
}

export interface CustomAgentDetail extends CustomAgentSummary {
  contents: Partial<Record<CustomAgentProviderId, string>>;
  manifests: Partial<Record<CustomAgentProviderId, {
    name: string;
    description?: string;
    developerInstructions?: string;
  }>>;
}

export interface CustomAgentListResponse {
  agents: CustomAgentSummary[];
}

export interface CreateCustomAgentRequest {
  provider: CustomAgentProviderId;
  content: string;
}

export interface UpdateCustomAgentRequest {
  content: string;
}

// ── Hub WebSocket protocol (multiplexed) ────────────────────────────

/** Client -> Server (hub-level). */
export type HubIncoming =
  | { type: "sync_workspaces"; workspaceIds: string[] }
  | { workspaceId: string; event: WsIncoming };

/** Server -> Client (hub-level). Every outgoing event is tagged with its workspace. */
export interface HubOutgoing {
  workspaceId: string;
  event: WsOutgoing;
}
