export interface Project {
  id: string;
  name: string;
  url: string;
  createdAt: string;
  workspaces: Workspace[];
  repoPath?: string;
  workspacesPath?: string;
  hasFavicon?: boolean;
}

export interface Workspace {
  id: string;
  name: string;
  branch: string;
  status: "idle" | "busy";
  createdAt: string;
  activeSessionId?: string;
  projectName?: string;
  defaultBranch?: string;
  worktreePath?: string;
}

// ── Tab types ───────────────────────────────────────────────────────

export type Tab =
  | { type: "session"; sessionId: string }
  | { type: "file"; path: string };

export type TabId = `session:${string}` | `file:${string}`;

export function tabId(tab: Tab): TabId {
  return tab.type === "session" ? `session:${tab.sessionId}` : `file:${tab.path}`;
}

export function parseTabId(id: TabId): Tab {
  if (id.startsWith("session:")) return { type: "session", sessionId: id.slice(8) };
  return { type: "file", path: id.slice(5) };
}

// ── Completion / autocomplete types ─────────────────────────────────

export type CompletionItemType = "slash_command" | "agent";
export type CompletionSource =
  | "builtin"
  | "user_skill"
  | "project_skill"
  | "plugin"
  | "user_agent"
  | "project_agent";

export interface CompletionItem {
  type: CompletionItemType;
  name: string;
  label: string;
  description?: string;
  argumentHint?: string;
  source: CompletionSource;
}

// ── Branch / GitHub sync types ──────────────────────────────────────

export interface PullRequestInfo {
  number: number;
  url: string;
  state: "open" | "draft" | "merged" | "closed";
  mergeable: boolean | null;
  mergeableState: "clean" | "conflict" | "blocked" | "unstable" | "unknown";
  checksStatus: "pending" | "success" | "failure" | "cancelled";
  checksPassed: number | null;
  checksTotal: number | null;
  reviewStatus: "approved" | "changes_requested" | "review_required" | null;
}

export interface BranchInfo {
  name: string;
  lastSyncedAt: string;
}

export interface PrStatusResponse {
  pr: PullRequestInfo | null;
  error?: string;
}

export interface BulkPrStatusResponse {
  results: Record<string, PrStatusResponse>;
}

export interface WorkspaceFileTreeNode {
  name: string;
  path: string;
  type: "file" | "directory";
  children?: WorkspaceFileTreeNode[];
}

export interface CreateProjectRequest {
  url: string;
}

// ── Queued message type ──────────────────────────────────────────────

export interface QueuedMessage {
  content: string;
  images?: ImageAttachment[];
  options?: MessageOptions;
  fileMentions?: FileMention[];
}

// ── Image attachment type ────────────────────────────────────────────

export interface ImageAttachment {
  name: string;
  mediaType: string;
  dataUrl: string;
}

// ── File mention type ───────────────────────────────────────────────

export interface FileMention {
  displayName: string;   // e.g. "git.ts" or "api/index.ts" (disambiguated)
  relativePath: string;  // e.g. "src/utils/git.ts"
}

// ── Session / Chat types ────────────────────────────────────────────

export interface SessionMetadata {
  sessionId: string;
  claudeSessionId?: string;
  workspaceId: string;
  title?: string;
  createdAt: string;
  updatedAt: string;
  messageCount: number;
  lockedProvider?: string;
}

export interface ToolCall {
  id: string;
  name: string;
  input: string;
  output?: string;
  parentToolUseId?: string;
}

export interface ChatMessage {
  id: string;
  sessionId: string;
  role: "user" | "assistant";
  content: string;
  images?: ImageAttachment[];
  fileMentions?: FileMention[];
  toolCalls?: ToolCall[];
  thinkingContent?: string;
  timestamp: string;
  cancelled?: boolean;
  /** Extra diagnostics for interrupted turns (stderr summary, exit code). */
  errorDetail?: string;
  durationMs?: number;
  /** Total input tokens sent to the model for this turn (= context usage). */
  inputTokens?: number;
  /** Output tokens generated by the model for this turn. */
  outputTokens?: number;
}

// ── Question / Plan types (for AskUserQuestion & ExitPlanMode tools) ─

export interface QuestionOption {
  label: string;
  description?: string;
}

export interface Question {
  question: string;
  header?: string;
  multiSelect?: boolean;
  options: QuestionOption[];
}

export interface QuestionAnswer {
  questionIndex: number;
  selectedOptions: number[];
  customText?: string;
}

export function isAskUserQuestion(tool: ToolCall): boolean {
  try {
    const input = JSON.parse(tool.input);
    return tool.name === "AskUserQuestion" && Array.isArray(input?.questions);
  } catch { return false; }
}

export function isExitPlanMode(tool: ToolCall): boolean {
  return tool.name === "ExitPlanMode";
}

export function parseQuestions(tool: ToolCall): Question[] {
  try {
    return JSON.parse(tool.input).questions ?? [];
  } catch { return []; }
}

// ── Script types ─────────────────────────────────────────────────────

export type ScriptType = string;
export type ScriptState = "idle" | "running" | "done" | "error";

export interface HiveConfig {
  scripts?: { setup?: string; run?: Record<string, string> };
  port?: number;
}

export interface ScriptStatusInfo {
  state: ScriptState;
  exitCode?: number;
}

export interface WorkspaceScriptsResponse {
  config: HiveConfig | null;
  status: Record<string, ScriptStatusInfo>;
}

// ── Diff types ───────────────────────────────────────────────────────

export type DiffFileStatus = "added" | "modified" | "deleted" | "renamed";

export interface DiffFileStat {
  file: string;
  additions: number;
  deletions: number;
  status: DiffFileStatus;
  renamedFrom?: string;
}

export interface DiffStatResponse {
  committed: DiffFileStat[];
  uncommitted: DiffFileStat[];
}

// ── Interactive tool input types ─────────────────────────────────────

export type ToolInputResult =
  | { type: "answer"; answers: QuestionAnswer[]; questions?: QuestionInput[] }
  | { type: "approve" }
  | { type: "reject"; message?: string }
  | { type: "dismiss"; message?: string };

export interface QuestionInput {
  question: string;
  options: Array<{ label: string; description?: string }>;
  multiSelect?: boolean;
}

// ── Per-message options ──────────────────────────────────────────────

export type ThinkingLevel = "low" | "medium" | "high" | "xhigh";

/** Per-message options that control agent CLI behavior. */
export interface MessageOptions {
  planMode?: boolean;
  thinkingEnabled?: boolean;
  /** Compound model ID: "provider:model", e.g. "claude:opus-4-6" */
  model?: string;
  /** Codex reasoning effort level (ignored by Claude provider). */
  thinkingLevel?: ThinkingLevel;
}

// ── Model catalog types ─────────────────────────────────────────────

export interface ProviderCapabilities {
  thinking: boolean | "levels";
  planMode: boolean;
  blockingTools: boolean;
  completions: boolean;
}

export interface ModelCatalogEntry {
  id: string;
  label: string;
  provider: string;
  providerLabel: string;
  isDefault?: boolean;
  isNew?: boolean;
  capabilities: ProviderCapabilities;
  /** Maximum context window size in tokens. */
  contextWindow?: number;
}

export interface ModelCatalogResponse {
  models: ModelCatalogEntry[];
  defaultModelId: string;
}

// ── WebSocket protocol ──────────────────────────────────────────────

/** Frontend -> Backend */
export type WsIncoming =
  | { type: "switch_session"; sessionId: string }
  | { type: "user_message"; content: string; images?: ImageAttachment[]; fileMentions?: FileMention[]; options?: MessageOptions; sessionId?: string }
  | { type: "stop"; sessionId?: string }
  | { type: "tool_input_response"; requestId: string; toolName: string; result: ToolInputResult; sessionId?: string };

/** Backend -> Frontend */
export type WsOutgoing =
  | { type: "text_delta"; sessionId: string; text: string }
  | { type: "thinking"; sessionId: string; text: string }
  | { type: "tool_use"; sessionId: string; id: string; name: string; input: string; parentToolUseId?: string }
  | { type: "tool_result"; sessionId: string; toolUseId: string; output: string }
  | { type: "tool_input_required"; sessionId: string; requestId: string; toolName: string; toolUseId: string; input: unknown }
  | { type: "done"; sessionId: string; durationMs?: number; inputTokens?: number; outputTokens?: number }
  | { type: "error"; message: string; sessionId?: string }
  | { type: "cancelled"; sessionId: string }
  | { type: "status"; status: "idle" | "busy"; sessionId?: string; streaming?: boolean; streamingStartedAt?: number; lockedProvider?: string }
  | { type: "user_message"; message: ChatMessage }
  | { type: "history"; messages: ChatMessage[]; sessionId?: string }
  | { type: "branch_info"; info: BranchInfo }
  | { type: "diff_stats"; stats: DiffStatResponse }
  | { type: "script_status"; scriptType: ScriptType; state: ScriptState; exitCode?: number }
  | { type: "plan_mode_changed"; sessionId: string; active: boolean };

// ── Automation types ─────────────────────────────────────────────────

export type AutomationTriggerType = "cron";
export type AutomationActionType = "agent";
export type AutomationRunStatus = "running" | "success" | "failure";

export interface AutomationTrigger {
  type: AutomationTriggerType;
  expression: string;
}

export interface AutomationAction {
  type: AutomationActionType;
  modelId: string;
  systemPromptId?: string;
  systemPromptInline?: string;
  userPromptId?: string;
  userPromptInline?: string;
}

export interface AutomationNotification {
  onComplete: boolean;
  onFailure: boolean;
}

export interface Automation {
  id: string;
  name: string;
  enabled: boolean;
  projectId?: string;
  trigger: AutomationTrigger;
  action: AutomationAction;
  notification: AutomationNotification;
  workspacePath?: string;
  lastRunId?: string;
  lastRunAt?: string;
  lastRunStatus?: AutomationRunStatus;
  createdAt: string;
  updatedAt: string;
}

export interface AutomationRun {
  id: string;
  automationId: string;
  status: AutomationRunStatus;
  sessionId: string;
  startedAt: string;
  completedAt?: string;
  durationMs?: number;
  summary?: string;
  error?: string;
}

export interface PromptTemplate {
  id: string;
  name: string;
  type: "system" | "user";
  content: string;
  createdAt: string;
  updatedAt: string;
}

export interface BasePromptData {
  content: string;
  isDefault: boolean;
  defaultContent: string;
}

// ── Hub WebSocket protocol (multiplexed) ────────────────────────────

/** Client -> Server (hub-level). */
export type HubIncoming =
  | { type: "sync_workspaces"; workspaceIds: string[] }
  | { workspaceId: string; event: WsIncoming };

/** Server -> Client (hub-level). Every outgoing event is tagged with its workspace. */
export interface HubOutgoing {
  workspaceId: string;
  event: WsOutgoing;
}
