import type { SetupErrorCode } from "@hive/shared/setup-errors";
import { isTauri } from "@/lib/is-tauri";

/**
 * Abstraction over the SSH sidecar that drives `provision.sh` on the target
 * server. The real implementation (Tauri + a Rust command that spawns the
 * system `ssh` binary) is Phase 2 work; the interface exists now so the wizard
 * is fully testable without Tauri via {@link createMockProvisionClient}.
 *
 * See docs/install-flow.md and docs/install-flow-implementation-plan.md §3.1
 * (NDJSON provision protocol) and §9 (wizard state machine).
 */

/** A discovered SSH key candidate under ~/.ssh (or a picked file). */
export interface SshKey {
  /** Absolute path to the private key file. Only the path is ever stored. */
  path: string;
  /** Display label, e.g. "id_ed25519". */
  label: string;
  /** Best-effort key type when known (ed25519, rsa, …). */
  type?: string;
  /** True when the file is passphrase-protected (needs an SSH_ASKPASS prompt). */
  encrypted?: boolean;
  /** True for a key Hive generated as the "no key" fallback. */
  generated?: boolean;
  /** Public key text — present for generated keys so the UI can show it to paste. */
  publicKey?: string;
}

export interface ProvisionParams {
  host: string;
  keyPath: string;
  /** Tailscale auth key (tskey-…), streamed over SSH stdin, never argv. */
  tailscaleAuthKey: string;
  /** The HIVE_AUTH_TOKEN generated by the app before install. */
  authToken: string;
  port?: number;
}

/**
 * A provision progress event. Mirrors the NDJSON protocol (§3.1) but normalized
 * into a tagged union the wizard renders directly. `seq` is strictly monotonic.
 */
export type ProvisionEvent =
  | {
      kind: "run_start";
      seq: number;
      runId: string;
      scriptVersion: string;
      resume: boolean;
      stepsPlanned: string[];
    }
  | { kind: "step_start"; seq: number; step: string; title: string }
  | { kind: "step_log"; seq: number; step: string; line: string; stream?: "stdout" | "stderr" }
  | { kind: "step_ok"; seq: number; step: string; durationMs?: number; data?: Record<string, unknown> }
  | { kind: "step_skip"; seq: number; step: string; reason?: string }
  | {
      kind: "step_error";
      seq: number;
      step: string;
      exitCode?: number;
      errorCode: SetupErrorCode;
      detail?: string;
    }
  | { kind: "run_end"; seq: number; status: "ok" | "error" };

export type TestConnectionResult = { fingerprint: string } | { error: SetupErrorCode };

export interface ProvisionClient {
  /** Discover candidate SSH keys under ~/.ssh (plus any picked/generated). */
  listKeys(): Promise<SshKey[]>;
  /**
   * Open an SSH connection and return the host-key fingerprint for the TOFU
   * dialog, or an error code (unreachable / auth failed / host key changed).
   */
  testConnection(host: string, keyPath: string): Promise<TestConnectionResult>;
  /** Persist the accepted host key into known_hosts (TOFU commit). */
  trustHost(host: string, fingerprint: string): Promise<void>;
  /** Start provisioning; yields NDJSON-derived events until run_end. */
  startProvision(params: ProvisionParams): AsyncIterable<ProvisionEvent>;
  /**
   * Re-attach to (or resume) a provision run after an error or app relaunch.
   * Skips already-completed steps and re-runs from the first non-ok step.
   */
  resumeProvision(host: string): AsyncIterable<ProvisionEvent>;
  /**
   * Run `claude setup-token` locally on the user's computer, open the browser,
   * and capture the resulting CLAUDE_CODE_OAUTH_TOKEN. The wizard POSTs it to
   * `/api/setup/auth/claude/token`. (Local flow — SSH/PTY are out of it.)
   */
  runLocalClaudeAuth(): Promise<{ token: string }>;
}

// ── Tauri implementation (Phase 2 — Rust side not wired yet) ─────────────────

const PHASE_2 = "provision SSH sidecar is not wired yet (Phase 2 Tauri/Rust work)";

/**
 * Real client backed by Tauri commands + events. The Rust commands
 * (`provision_list_keys`, `provision_test_connection`, `provision_trust_host`,
 * `provision_start`/`provision_resume` emitting `provision://event`, and
 * `provision_claude_auth`) are Phase 2 deliverables; until they exist these
 * methods throw a clear, marked error rather than silently failing.
 *
 * TODO(Phase 2): implement the Rust side and replace the throwing bodies below
 * with `invoke(...)` + an event-channel → AsyncIterable adapter.
 */
export function createTauriProvisionClient(): ProvisionClient {
  async function invoke<T>(cmd: string, args?: Record<string, unknown>): Promise<T> {
    const { invoke } = await import("@tauri-apps/api/core");
    return invoke<T>(cmd, args);
  }

  return {
    async listKeys() {
      // TODO(Phase 2): return await invoke<SshKey[]>("provision_list_keys");
      return invoke<SshKey[]>("provision_list_keys");
    },
    async testConnection(host, keyPath) {
      // TODO(Phase 2): return await invoke<TestConnectionResult>("provision_test_connection", { host, keyPath });
      return invoke<TestConnectionResult>("provision_test_connection", { host, keyPath });
    },
    async trustHost(host, fingerprint) {
      // TODO(Phase 2): await invoke("provision_trust_host", { host, fingerprint });
      await invoke("provision_trust_host", { host, fingerprint });
    },
    startProvision() {
      // TODO(Phase 2): bridge the Tauri `provision://event` channel to an AsyncIterable.
      throw new Error(PHASE_2);
    },
    resumeProvision() {
      // TODO(Phase 2): same bridge as startProvision, with resume=true.
      throw new Error(PHASE_2);
    },
    async runLocalClaudeAuth() {
      // TODO(Phase 2): return await invoke<{ token: string }>("provision_claude_auth");
      return invoke<{ token: string }>("provision_claude_auth");
    },
  };
}

// ── Mock implementation (dev + tests) ────────────────────────────────────────

export type MockScenario = "happy" | "error";

/** A scripted sequence used to build the mock's event stream. */
export interface MockScript {
  keys?: SshKey[];
  connection?: TestConnectionResult;
  claudeToken?: string;
  events: ProvisionEvent[];
  /** Delay between yielded events, ms (0 in tests). */
  delayMs?: number;
}

const DEFAULT_KEYS: SshKey[] = [
  { path: "/home/user/.ssh/id_ed25519", label: "id_ed25519", type: "ed25519" },
  { path: "/home/user/.ssh/id_rsa", label: "id_rsa", type: "rsa", encrypted: true },
];

const HAPPY_STEPS: Array<{ step: string; title: string }> = [
  { step: "probe_os", title: "Check server OS" },
  { step: "tailscale_up", title: "Join the tailnet" },
  { step: "apt_baseline", title: "Install Node, git, firewall" },
  { step: "install_release", title: "Install the Hive release" },
  { step: "start_service", title: "Start Hive" },
];

function buildHappyEvents(): ProvisionEvent[] {
  let seq = 0;
  const events: ProvisionEvent[] = [
    {
      kind: "run_start",
      seq: seq++,
      runId: "r-mock",
      scriptVersion: "0.3.0",
      resume: false,
      stepsPlanned: HAPPY_STEPS.map((s) => s.step),
    },
  ];
  for (const { step, title } of HAPPY_STEPS) {
    events.push({ kind: "step_start", seq: seq++, step, title });
    events.push({ kind: "step_log", seq: seq++, step, line: `Running ${step}…` });
    events.push({ kind: "step_ok", seq: seq++, step, durationMs: 1000 });
  }
  events.push({ kind: "run_end", seq: seq++, status: "ok" });
  return events;
}

function buildErrorEvents(): ProvisionEvent[] {
  let seq = 0;
  const failAt = 1; // fail on tailscale_up
  const events: ProvisionEvent[] = [
    {
      kind: "run_start",
      seq: seq++,
      runId: "r-mock",
      scriptVersion: "0.3.0",
      resume: false,
      stepsPlanned: HAPPY_STEPS.map((s) => s.step),
    },
  ];
  for (let i = 0; i <= failAt; i++) {
    const { step, title } = HAPPY_STEPS[i];
    events.push({ kind: "step_start", seq: seq++, step, title });
    if (i === failAt) {
      events.push({ kind: "step_log", seq: seq++, step, line: "backend error: invalid key", stream: "stderr" });
      events.push({
        kind: "step_error",
        seq: seq++,
        step,
        exitCode: 1,
        errorCode: "TS_AUTHKEY_INVALID",
        detail: "backend error: invalid key",
      });
    } else {
      events.push({ kind: "step_ok", seq: seq++, step, durationMs: 1000 });
    }
  }
  events.push({ kind: "run_end", seq: seq++, status: "error" });
  return events;
}

/** Events for a resume after the error path: the failed step now succeeds. */
function buildResumeEvents(): ProvisionEvent[] {
  let seq = 100;
  const events: ProvisionEvent[] = [
    {
      kind: "run_start",
      seq: seq++,
      runId: "r-mock",
      scriptVersion: "0.3.0",
      resume: true,
      stepsPlanned: HAPPY_STEPS.map((s) => s.step),
    },
  ];
  // Steps before the failure are skipped; the rest run and succeed.
  events.push({ kind: "step_skip", seq: seq++, step: "probe_os", reason: "already-satisfied" });
  for (let i = 1; i < HAPPY_STEPS.length; i++) {
    const { step, title } = HAPPY_STEPS[i];
    events.push({ kind: "step_start", seq: seq++, step, title });
    events.push({ kind: "step_ok", seq: seq++, step, durationMs: 1000 });
  }
  events.push({ kind: "run_end", seq: seq++, status: "ok" });
  return events;
}

function scenarioScript(scenario: MockScenario): MockScript {
  if (scenario === "error") {
    return {
      keys: DEFAULT_KEYS,
      connection: { fingerprint: "SHA256:mock-fingerprint" },
      claudeToken: "sk-ant-oat01-mock",
      events: buildErrorEvents(),
      delayMs: 0,
    };
  }
  return {
    keys: DEFAULT_KEYS,
    connection: { fingerprint: "SHA256:mock-fingerprint" },
    claudeToken: "sk-ant-oat01-mock",
    events: buildHappyEvents(),
    delayMs: 0,
  };
}

/**
 * A fully in-memory ProvisionClient that replays a scripted sequence of
 * ProvisionEvents. Used by dev and tests; the wizard depends only on the
 * ProvisionClient interface, so swapping this for the Tauri client is a
 * one-line change at the composition root.
 */
export function createMockProvisionClient(
  scenario: MockScenario | MockScript = "happy",
): ProvisionClient {
  const script: MockScript =
    typeof scenario === "string" ? scenarioScript(scenario) : scenario;
  const delay = script.delayMs ?? 0;

  async function* stream(events: ProvisionEvent[]): AsyncIterable<ProvisionEvent> {
    for (const event of events) {
      if (delay > 0) await new Promise((r) => setTimeout(r, delay));
      yield event;
    }
  }

  return {
    async listKeys() {
      return script.keys ?? DEFAULT_KEYS;
    },
    async testConnection() {
      return script.connection ?? { fingerprint: "SHA256:mock-fingerprint" };
    },
    async trustHost() {
      // no-op in the mock
    },
    startProvision() {
      return stream(script.events);
    },
    resumeProvision() {
      // On resume, replay a run that skips completed steps and succeeds.
      return stream(buildResumeEvents());
    },
    async runLocalClaudeAuth() {
      return { token: script.claudeToken ?? "sk-ant-oat01-mock" };
    },
  };
}

/**
 * Choose the appropriate client for the current runtime. In Tauri, use the real
 * (Phase-2) SSH sidecar; otherwise fall back to the mock so the web/dev build
 * and tests keep working.
 */
export function createProvisionClient(): ProvisionClient {
  return isTauri() ? createTauriProvisionClient() : createMockProvisionClient("happy");
}
